{
    'name': 'Car Service',
    'version': '16.0.0.0.1',
    'category': 'Extra Tools',
    'summary': """Car service station automation module 
    """,
    'license': 'LGPL-3',
    'author': 'Yaroslav Artiushenko',
    'website': 'https://github.com/Kankitsuuu',
    'depends': [
        'base',
    ],
    'data': [
        'security/car_service_groups.xml',
        'security/ir.model.access.csv',
        'security/car_service_security.xml',
        'data/car_service_service_category.xml',
        'data/car_service_client_car_color.xml',
        'views/car_service_menus.xml',
        'views/car_service_worker_views.xml',
        'views/car_service_client_views.xml',
        'views/car_service_client_car_views.xml',
        'views/car_service_client_car_make_views.xml',
        'views/car_service_client_car_color_views.xml',
        'views/car_service_service_views.xml',
        'views/car_service_service_category_views.xml',
        'views/car_service_provided_service_views.xml',
        'views/car_service_invoice_views.xml',
        'wizard/change_service_price_wizard_views.xml',
        'wizard/change_service_category_wizard_views.xml',
        'wizard/create_invoice_wizard_views.xml',
        'reports/car_service_invoice.xml',
        'reports/car_service_invoice_template.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/car_service_client_demo.xml',
        'demo/car_service_worker_demo.xml',
        'demo/car_service_client_car_make_demo.xml',
        'demo/car_service_client_car_demo.xml',
        'demo/car_service_service_demo.xml',
    ],
    'support': 'artiuschenko01@gmail.com',
    'application': False,
    'installable': True,
    'auto_install': False,
}